### ISSUE TITLE
Australian Brand Arlec Grid Connect - Dimmable Light

### ISSUE THREAD

**Issue by mitch7391** [iRayanKhan/homebridge-tuya-platform#11]
@iRayanKhan I have installed you version of this and gave it a go today and am facing the same issues as I was in homebridge-tuya-lan. Here is an issue I raised recently that details my issue more:

https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/159

Here is the original issue I hijacked:

https://github.com/AMoo-Miki/homebridge-tuya-lan/issues/114

I spent a very long time trying to get the ID using the prescribed method and found that it only worked once I used version rc-11 or rc-12. I finally got my ID and was able to add my device, however it just wont control.

Just really frustrated with this light and want to get it going, so I am glad you have picked up this plug-in. This was supposed to be be a cheap and easy 'test the waters' with Arlec's new smart devices, as if this works I will be buying their smart light switches and smart fan to hopefully get into Homekit too. Please let me know if you need anymore information.

**Comment by iRayanKhan** [comment]
Hi what is the output you get when trying to control the device?

**Comment by mitch7391** [comment]
Light is reporting as off in Homekit whilst it iss actually on (reports as on in Grid Connect app). The state only changes in Homekit based on the commands I issue from Homekit (under the assumption the command was successful I assume), however this does not physically change the state of the light.

What I see in homebridge when I turn the light off and on in Homekit:

[TuyaAccessory] Sending Smart Lamp {"2":255}
[TuyaAccessory] Sending Smart Lamp {"1":true}
[TuyaAccessory] Sending Smart Lamp {"1":false}

I have tried both SimpleLight and SimpleDimmer and get the same results. This is a light that is one colour temperature and has dimming functionality.

Here is what I see in my homebridge logs when I turn the lamp off and on through the Grid Connect app:

[TuyaAccessory] Heard back from Smart Lamp with command 8
[TuyaAccessory] Heard back from Smart Lamp with command 8

This is what I see in homebridge logs when I brighten the light from 50% to 100% in the Grid Connect app:

[TuyaAccessory] Heard back from Smart Lamp with command 8

However, nothing changes in Homekit at all.

**Comment by iRayanKhan** [comment]
So Command 8 means it's using an unknown API. 

If you can follow the instruction at the end of [this](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Common-Problems) wiki page, I can try (no guarantees) to see if I can implement this into the plugin. And instead of the Email listed there send it to ``` rayankhan04 [@] iCloud.com```

**Comment by mitch7391** [comment]
Interesting that would explain a lot. Would have been good if the other developer had responded to me and saved me all the time Iv wasted trying to set this up... I was told this is a rebranded Tuya app, but maybe it’s different. I will follow the steps and get back to you :) hopefully I will have some time this evening.

**Comment by mitch7391** [comment]
I feel like that these steps have a bunch of assumed knowledge. As someone who isn’t a Mac user, using his Fiancée’s Mac, I am stuck on step 10. Am I typing that into terminal? I tried in there and it says ‘-bash: rvictl: command not found’. 

Are there steps to do this on windows where I am a bit more comfortable?

**Comment by mitch7391** [comment]
So I googled and found that I need to install X-code on her Mac to get the additional tools, problem is she has no space on her Mac. @iRayanKhan is there a way to do all of this on Windows10? If not I will have to negotiate some space haha...

**Comment by iRayanKhan** [comment]
Hi @mitch7391 sorry for the delay,
I personally use all mac's let me do some research on a way to do it from Windows. 
Xcode does indeed take much storage on macOS, because it has a lot of device support files on it.

I will get back to you asap.

**Comment by mitch7391** [comment]
No worries @iRayanKhan, would be good to learn how to do his stuff and always willing to try help out if I can; just need a little guidance haha.

**Comment by iRayanKhan** [comment]
If you need guidance, look at the index file and the other accessory files to see how an accessory is made. I have to do some research on how to add it since I haven't tinkered with a humidifier accessory (in home bridge) yet.

**Comment by beef-techau** [comment]
I’m in the same boat as Mitch, I’ve got device id  and key, I’ve managed to get the device into home app via homebridge however it’s unresponsive. 
It’s an Arlec Smart LED Globe RGB from bunnings. 
I bought it as a tester because it will be a financially better option to replace lights with arlec (tuya) options rather than HomeKit verified options. 
I used tuya-lan-find - - schema and then paired the globe in grid connect app to get the device id and key.

**Comment by mitch7391** [comment]
@L4RGER as @iRayanKhan has said it looks like the API used for our Arlec devices must be different somehow and hence why we can connect them but commands do not work. Until he or someone else is able to work out the API then it sounds like we are stuck.

**Comment by L4RGER** [comment]
@mitch7391,
Have you got a SmartThings hub? If these arlec globes work through SmartThings, and then use the SmartThings plugin should be sweet. 
I’m just in the process of buying a house so trying to sort a few things out before hand, so if I bought a s/things hub now it would literally be for one light globe haha 
But I’ve seen it quoted that between HomeKit and smart things just about every smart device can be controlled

**Comment by beef-techau** [comment]
> So Command 8 means it's using an unknown API.
> 
> If you can follow the instruction at the end of [this](https://github.com/AMoo-Miki/homebridge-tuya-lan/wiki/Common-Problems) wiki page, I can try (no guarantees) to see if I can implement this into the plugin. And instead of the Email listed there send it to ` rayankhan04 [@] iCloud.com`

@iRayanKhan, I’m getting command 10 which is different to what @mitch7391. Hopefully
I get some time later today and will try to follow the steps to debug
![4922546A-6586-4395-8312-9B93926C20CA](https://user-images.githubusercontent.com/61365310/75125444-e3b30c00-5700-11ea-9d22-113866f1b9a1.jpeg)

**Comment by iRayanKhan** [comment]
I wonder if there are US version of these devices. I am not sure how to crack this specific API, but can look further to see what can be done. Tuya is such an obscure framework for devices lol

**Comment by mitch7391** [comment]
I was able to get this light to work using the Smart Life app and the homebridge-tuya-web plug-in. Thanks for your efforts.

**Comment by iRayanKhan** [comment]
Sorry for not being able to get it In time, glad it's working for you.
