### ISSUE TITLE
Extracting Keys

### ISSUE THREAD

**Issue by MikeDProducer** [iRayanKhan/homebridge-tuya-platform#13]
Greetings. I love this project. Are you working on an updated way to extract the keys from Tuya? As I understand it, they’ve changed it to make this more difficult. Methods that are recommended no longer work.

**Comment by MikeDProducer** [comment]
I tried this and it didn’t work. I also attempted another method using Burp. I’ve read that Tuya changed something where it doesn’t deliver the key information r try he same way as they used to. But I don’t know much about it.

**Comment by iRayanKhan** [comment]
Hi @MikeDProducer, try the uComen home app to get the keys.

**Comment by MikeDProducer** [comment]
That worked. Thank you!
