### ISSUE TITLE
Can't extract keys through various apps

### ISSUE THREAD

**Issue by bugs181** [iRayanKhan/homebridge-tuya-platform#14]
So far, I have tried the following apps with no success:

- TuyaSmart
- Geeni
- Smart Life
- CE Smart
- UcomenHome

I have followed the instructions to the letter. I've setup this plugin before but it's been a while and I just purchased some new devices to add again. I'm well aware of the steps it takes and I repeated the same steps as last time.

On every app I've tried, I receive "Network Error, Please Retry"

To me, it appears Tuya released an update that broke this method.

**Comment by iRayanKhan** [comment]
Yeah I guess the api has broken. Looks like I have to find a workaround.

**Comment by iRayanKhan** [comment]
Ucomen should still work to get keys, is your device un-added from the other apps?

**Comment by bugs181** [comment]
> Ucomen should still work to get keys, is your device un-added from the other apps?

Yes, it’s directly out of box. Never connected before. I’ve since switched to tasmota so unfortunately can not diagnose the issue further.

**Comment by iRayanKhan** [comment]
Is the Tasmota working? If so Can I close this issue?

**Comment by iRayanKhan** [comment]
Closing:
Assuming you got Tasmota working.
