### ISSUE TITLE
Tuya-Lan-Find can't connect to port 8080 - Hoobs

### ISSUE THREAD

**Issue by Mikmonken** [iRayanKhan/homebridge-tuya-platform#4]
I think this is something that you came up with previously, as I see your Ucomen Home solution involved changing the port, but I've come across this too.

I'm not savvy enough to know where to change that file, but as I use HOOBS (which I think defaults to 8080) I could change the port here and get Tuya Lan Find to work by switching it to 8001.

Though it useful to flag anyway for info.

**Comment by iRayanKhan** [comment]
Thanks for the heads up, I haven't used hoobs, but I'll add this to the wiki if other users encounter this issue.
